<h1>Hello World!</h1>

<div class="actions">
    <button class="action subscribe primary"  type="submit" id="back" onclick="back()"> B a c k </button>
    <br>
    <br>
</div>

<p>A hello message in a simple module example for magento 2</p>

<script>
    function back(){
        window.location.href = "http://aventidev.local/magento/hello";

    };

    document.addEventListener("DOMContentLoaded", function (){
        document.getElementById('hello').style.display = 'none';
    });

</script>



